---
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
    options:
      memory: 512
      cpus: 1
platforms:
  - name: node1
    box: debian/bookworm64
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.56.10
    groups:
      - debian
      - keepalived

  - name: node2
    box: debian/bookworm64
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.56.20
    groups:
      - debian
      - keepalived
  
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
    ansible_command_timeout: 30
  log: true

scenario:
  name: basic-debian
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - destroy
